on:
  push:
    tags:
      - "v*"

jobs:
  export_game:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: .
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}

      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
